### 广播

In [1]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

### 访问元素

元素的索引从 0 开始。对各个元素的访问可按如下方式进行。

In [4]:
X = np.array([[51,55],[14,19],[0,4]])
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [5]:
X[0] # 第0行

array([51, 55])

In [6]:
X[0][1] # (0,1)的元素

np.int64(55)

也可以使用 for 语句访问各个元素。

In [8]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


除了前面介绍的索引操作,NumPy 还可以使用数组访问各个元素。

In [10]:
X = X.flatten()
X

array([51, 55, 14, 19,  0,  4])

In [12]:
X[np.array([0,2,4])] # 获取索引为 0、2、4 的元素

array([51, 14,  0])