#### 一维数组

In [2]:
import numpy as np
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [3]:
A.ndim

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

#### 二维数组

In [6]:
B = np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
B.ndim

2

In [8]:
B.shape

(3, 2)

In [9]:
B.shape[0]

3

#### 数组乘法

In [11]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A * B

array([[ 5, 12],
       [21, 32]])

In [12]:
# 点乘
np.dot(A,B)

array([[19, 22],
       [43, 50]])

#### 2 × 3 的矩阵和 3 × 2 的矩阵的乘积可按如下形式用 Python 来实现。

In [13]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [19]:
A.ndim

2

In [14]:
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

In [20]:
B.ndim

2

In [15]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [17]:
np.dot(B,A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

#### A 是二维矩阵、B 是一维数组

In [21]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])
np.dot(A,B)

array([23, 53, 83])

In [23]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)
Y

array([ 5, 11, 17])