#### softmax

In [2]:
import numpy as np

In [3]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a) # 指数函数
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [4]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [6]:
y = exp_a / sum_exp_a
print(y)

[0.01821127 0.24519181 0.73659691]


In [7]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

In [10]:
a = np.array([1010,1000,990])
print(np.exp(a) / np.sum(np.exp(a)))

[nan nan nan]


/var/folders/hx/vrwsgqgx7bncbt28n44f0b540000gn/T/ipykernel_26797/2582085374.py:2: RuntimeWarning: overflow encountered in exp
  print(np.exp(a) / np.sum(np.exp(a)))
/var/folders/hx/vrwsgqgx7bncbt28n44f0b540000gn/T/ipykernel_26797/2582085374.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.exp(a) / np.sum(np.exp(a)))


In [12]:
c = np.max(a)
print(a-c)
print(np.exp(a-c) / np.sum(np.exp(a-c)))

[  0 -10 -20]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [13]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [14]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [15]:
print(np.sum(y))

1.0
